#
# Docker file for CI on Ubuntu LTS
#
FROM ubuntu:resolute

# prepare
RUN apt-get update -qq
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-deb.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb.sh && /build/ci/install-deps-deb.sh

# finish
WORKDIR /build
